### ISSUE TITLE
error json in crawl

### ISSUE THREAD

**Issue by lacroutelacroute** [segment-srl/htcap#28] opened 2017-05-03 09:21 UTC
iam bugbounty hunter
i test use htcap
and i have recurent error
i use up to date 
~$ phantomjs --version
2.1.1

please descrive the solution

/opt/htcap/htcap$ sudo python ./htcap.py crawl  -m aggressive  -H https://www.xxxxxx.fr/fr/index.html  cicfr.db
Initializing . . . done
Database cicfr.db initialized, crawl started with 10 threads
[                                 ]   0 of 31 pages processed in 0 minutesException in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/htcap/htcap/core/crawl/crawler_thread.py", line 62, in run
    self.crawl()
  File "/opt/htcap/htcap/core/crawl/crawler_thread.py", line 215, in crawl
    probe = self.send_probe(request, errors)
  File "/opt/htcap/htcap/core/crawl/crawler_thread.py", line 164, in send_probe
    probeArray = self.load_probe_json(jsn)
  File "/opt/htcap/htcap/core/crawl/crawler_thread.py", line 99, in load_probe_json
    return json.loads(jsn)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Exception in thread Thread-2:

**Comment by segment-srl** [comment] 2017-05-03 10:01
Hi, this is a duplicate of issue #11. The problem is related to some phantomjs builds. You should try to use the one from the vendor website (http://phantomjs.org/download.html) and remove the one installed via apt.

**Closed by segment-srl** 2017-05-03 10:01 UTC

**Comment by GuilloOme** [comment] 2017-05-03 13:00
@lacroutelacroute, can you confirm that the phantomjs binary you use come from the project himself (there is a known bug related to the binary provided by the ubuntu repo)?
Plus, you can try out with my fork here: https://github.com/delvelabs/htcap I did a lot of work in this part of the app to fix these kind of bugs (and others). Feel free to open a bug there if needed.

**Comment by lacroutelacroute** [comment] 2017-05-03 15:48
The problem of precompiles binaries you know it are difficult to update. I hope that the original htcap developer will update his software to not be victim of this bug
