### ISSUE TITLE
Extra error when crawling 

### ISSUE THREAD

**Issue by barhaterahul** [segment-srl/htcap#11] opened 2017-01-22 08:13 UTC
I was trying to crawl a website with -m active -v. I am getting these errors. Could you please look into it,
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/Desktop/htcap/core/crawl/crawler_thread.py", line 62, in run
    self.crawl()
  File "/root/Desktop/htcap/core/crawl/crawler_thread.py", line 215, in crawl
    probe = self.send_probe(request, errors)
  File "/root/Desktop/htcap/core/crawl/crawler_thread.py", line 164, in send_probe
    probeArray = self.load_probe_json(jsn)
  File "/root/Desktop/htcap/core/crawl/crawler_thread.py", line 99, in load_probe_json
    return json.loads(jsn)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 1 - line 5 column 249 (char 69 - 317)

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/root/Desktop/htcap/core/crawl/crawler_thread.py", line 62, in run
    self.crawl()
  File "/root/Desktop/htcap/core/crawl/crawler_thread.py", line 215, in crawl
    probe = self.send_probe(request, errors)
  File "/root/Desktop/htcap/core/crawl/crawler_thread.py", line 164, in send_probe
    probeArray = self.load_probe_json(jsn)
  File "/root/Desktop/htcap/core/crawl/crawler_thread.py", line 99, in load_probe_json
    return json.loads(jsn)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 5 column 1 - line 5 column 249 (char 341 - 589)

**Comment by GuilloOme** [comment] 2017-01-27 17:19
I had the same error…

Here is the content of the problematic json:
```json
[
["cookies",[]],
{"status":"ok","redirect":"http://blog.jlr.ca/category/rapport-trimestriel","time":0}
]
Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.{"status":"ok", "partialcontent":true}]
```

There is clearly some garbage in it…

**Comment by segment-srl** [comment] 2017-01-28 13:50
Thanks! It's clearly some garbage generated by phantomjs. 
Could you please provide steps to reproduce the problem?

**Comment by GuilloOme** [comment] 2017-01-28 15:18
I've got the error while crawling one of our client website, I tried to reproduce it in a more stable environment without success. Sorry…

I'll try again next week

**Comment by GuilloOme** [comment] 2017-01-30 14:49
Finally, I found a way to reproduce:

- run `analyse.js` on a local path: `$ phantomjs core/crawl/probe/analyze.js /`

- It returns the same type of garbage:

```json
[
{"status":"error","code":"load","time":0}
]
Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.
```

**Comment by segment-srl** [comment] 2017-02-06 15:09
thanks!!

**Comment by GuilloOme** [comment] 2017-02-15 18:34
It looks like the error happened every time PhantomJS hits a redirect…
It became a blocker for us here, so I'm starting to work on a fix.

**Comment by segment-srl** [comment] 2017-02-15 20:30
I'm still unable to reproduce this issue, even with "phantomjs core/crawl/probe/analyze.js /". What version of phantomjs are you using on what os?

**Comment by GuilloOme** [comment] 2017-02-15 20:32
```
$ phantomjs --version
2.1.1
```

**Comment by segment-srl** [comment] 2017-02-15 20:33
linux?

**Comment by GuilloOme** [comment] 2017-02-15 20:36
Yes linux…
This is interesting: I don't get the same result with the binary provided by the ubuntu repo and with the one downloaded on project page!
With the one for the project, I don't get any error…

**Comment by segment-srl** [comment] 2017-02-15 20:41
interesting yes.. so it's an issue related on the phantomjs build.. one solution is to write analize,js output to fie instead of stdout..

**Comment by GuilloOme** [comment] 2017-02-15 21:30
I check the build difference between the 2 build (project vs ubuntu repo) and it seems that the ubuntu on do not use the same process for building PhantomJS.
I asked them why here: https://answers.launchpad.net/ubuntu/+source/phantomjs/+question/462517

**Comment by GuilloOme** [comment] 2017-02-16 13:32
@barhaterahul, what version of PhantomJS do you run? Is it the version provided by Ubuntu too?

**Comment by GuilloOme** [comment] 2017-03-07 14:17
Finally, my question at launchpad regarding the difference with the build process has been closed without a straight answer…
So, I updated the readme: #20

**Comment by segment-srl** [comment] 2017-07-31 13:16
This issue is related to phantomjs build on some linux distros. Using the binary from the officail website should fix the problem. 
Since phantomjs is no more supported, htcap is now moving to headless chrome so issue similar to this one won't be fixed.

**Closed by segment-srl** 2017-07-31 13:16 UTC
